const TodoConstants = {
  GET_ALL_TODOS: "GET_ALL_TODOS",
  GET_COMPLETED_TODOS: "GET_COMPLETED_TODOS",
  SET_COMPLETED_TODOS: "SET_COMPLETED_TODOS",
  GET_PENDING_TODOS: "GET_PENDING_TODOS", 
  DELETE_COMPLETED_TODOS: "DELETE_COMPLETED_TODOS",
  SET_ROUTES: "SET_ROUTES"
}

export default TodoConstants;